# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20170614_1607'),
        ('core', '0005_auto_20170614_1607'),
        ('shimmy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPNCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Item Name')),
                ('invoiceNumber', models.CharField(max_length=50, verbose_name='Invoice Item Number')),
                ('mc_gross', models.FloatField(default=0, verbose_name='Gross Amount')),
                ('refundAmount', models.FloatField(default=0, verbose_name='Allocated Refund Amount')),
            ],
            options={
                'verbose_name': 'Paypal IPN Cart Item',
            },
        ),
        migrations.CreateModel(
            name='IPNMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('invoice', models.CharField(max_length=80, verbose_name='Invoice number')),
                ('generated_invoice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paypal-generated invoice number')),
                ('mc_fee', models.FloatField()),
                ('mc_gross', models.FloatField()),
                ('payment_status', models.CharField(max_length=30)),
                ('payment_date', models.DateTimeField()),
                ('txn_id', models.CharField(max_length=30, unique=True)),
                ('txn_type', models.CharField(max_length=30)),
                ('custom', models.TextField()),
                ('mc_currency', models.CharField(max_length=30)),
                ('payer_email', models.EmailField(max_length=254)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('payer_id', models.CharField(max_length=30)),
                ('finalRegistration', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Registration', verbose_name='Final Registration')),
                ('invoiceObject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Invoice', verbose_name='Registration Invoice')),
                ('priorTransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsequenttransactions', to='shimmy.IPNMessage')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TemporaryRegistration', verbose_name='Initial Temporary Registration')),
            ],
            options={
                'verbose_name': 'Paypal IPN message',
            },
        ),
        migrations.AddField(
            model_name='ipncartitem',
            name='ipn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shimmy.IPNMessage'),
        ),
        migrations.AddField(
            model_name='ipncartitem',
            name='revenueItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.RevenueItem'),
        ),
    ]
